version: '3'

services:
  db:
    image: postgis/postgis:15-3.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: d2qc
      POSTGRES_PASSWORD: d2qc
      POSTGRES_DB: d2qc
    ports:
      - "5432:5432"

  web:
    build: .
    command: /app/entrypoint.sh gunicorn d2qc.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=d2qc.setup.development
      - DJANGO_DEBUG=True
    volumes:
      - static_data:/static
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
      - static_data:/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
