# Generated by Django 2.1.dev20180428173945 on 2018-11-02 10:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cast', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'd2qc_casts',
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('headers', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'd2qc_data_files',
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_reference', models.BooleanField(default=False)),
                ('expocode', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sets', to='data.DataFile')),
            ],
            options={
                'db_table': 'd2qc_data_sets',
                'ordering': ['expocode'],
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, default='', max_length=20)),
                ('prefLabel', models.CharField(blank=True, default='', max_length=255)),
                ('altLabel', models.CharField(blank=True, default='', max_length=255)),
                ('definition', models.CharField(blank=True, default='', max_length=255)),
                ('original_label', models.CharField(default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'd2qc_data_types',
            },
        ),
        migrations.CreateModel(
            name='DataUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, default='', max_length=20)),
                ('prefLabel', models.CharField(blank=True, default='', max_length=255)),
                ('altLabel', models.CharField(blank=True, default='', max_length=255)),
                ('definition', models.CharField(blank=True, default='', max_length=255)),
                ('original_label', models.CharField(default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'd2qc_data_units',
            },
        ),
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=8, max_digits=16)),
                ('qc_flag', models.IntegerField(blank=True, null=True)),
                ('qc2_flag', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DataType')),
            ],
            options={
                'db_table': 'd2qc_data_values',
            },
        ),
        migrations.CreateModel(
            name='Depth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('depth', models.DecimalField(decimal_places=3, max_digits=8)),
                ('date_and_time', models.DateTimeField()),
                ('bottle', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depths', to='data.Cast')),
            ],
            options={
                'db_table': 'd2qc_depths',
                'ordering': ['depth'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('station_number', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='data.DataSet')),
            ],
            options={
                'db_table': 'd2qc_stations',
                'ordering': ['data_set', 'station_number'],
            },
        ),
        migrations.AddField(
            model_name='datavalue',
            name='depth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_values', to='data.Depth'),
        ),
        migrations.AddField(
            model_name='datatype',
            name='data_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DataUnit'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_types',
            field=models.ManyToManyField(blank=True, related_name='data_sets', to='data.DataType'),
        ),
        migrations.AddField(
            model_name='cast',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='data.Station'),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('position', 'station_number', 'data_set')},
        ),
        migrations.AddIndex(
            model_name='depth',
            index=models.Index(fields=['depth'], name='d2qc_depths_depth_8f73f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='depth',
            unique_together={('cast', 'depth', 'bottle', 'date_and_time')},
        ),
        migrations.AlterUniqueTogether(
            name='datavalue',
            unique_together={('depth', 'data_type')},
        ),
        migrations.AlterUniqueTogether(
            name='datatype',
            unique_together={('original_label', 'identifier', 'data_unit')},
        ),
    ]
