# Generated by Django 2.1.dev20180428173945 on 2018-05-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('depth', models.DecimalField(decimal_places=3, max_digits=8)),
                ('unix_time_millis', models.BigIntegerField()),
                ('station_number', models.IntegerField()),
            ],
            options={
                'db_table': 'd2qc_datapoints',
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expocode', models.CharField(max_length=255)),
                ('is_reference', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'd2qc_datasets',
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'd2qc_datatypes',
            },
        ),
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=10, max_digits=19)),
                ('data_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DataPoint')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DataType')),
            ],
            options={
                'db_table': 'd2qc_datavalues',
            },
        ),
        migrations.AddField(
            model_name='datapoint',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DataSet'),
        ),
    ]
