# Generated by Django 2.1.dev20180428173945 on 2018-11-07 11:14

from django.db import migrations
import os


class Migration(migrations.Migration):

    def __init__(self, name, app_label):
        path = os.path.join(os.path.dirname(__file__), name) + '.sql'
        with open(path, 'r') as sqlfile:
            rawsql=sqlfile.read()
            self.operations.append(migrations.RunSQL(rawsql))
        super().__init__(name, app_label)


    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
    ]
