# Generated by Django 2.1.dev20180428173945 on 2018-05-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180505_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, default='', max_length=20)),
                ('prefLabel', models.CharField(blank=True, default='', max_length=255)),
                ('altLabel', models.CharField(blank=True, default='', max_length=255)),
                ('definition', models.CharField(blank=True, default='', max_length=255)),
                ('original_label', models.CharField(default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'd2qc_dataunits',
            },
        ),
        migrations.AddField(
            model_name='datatype',
            name='altLabel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='datatype',
            name='definition',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='datatype',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='datatype',
            name='original_label',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='datatype',
            name='prefLabel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='unit',
        ),
        migrations.AddField(
            model_name='datatype',
            name='data_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DataUnit'),
        ),
        migrations.AlterUniqueTogether(
            name='datatype',
            unique_together={('identifier', 'original_label')},
        ),
    ]
