# Generated by Django 2.1.dev20180428173945 on 2018-11-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181107_1114'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE d2qc_data_sets_data_types;')
    ]
