# Generated by Django 2.1.dev20180428173945 on 2018-08-29 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180508_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='data.DataSet'),
        ),
        migrations.AlterField(
            model_name='datavalue',
            name='data_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='data.DataPoint'),
        ),
    ]
