# Generated by Django 2.1.dev20180428173945 on 2018-05-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180508_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='station_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='datatype',
            unique_together=set(),
        ),
    ]
