# Generated by Django 2.1.dev20180428173945 on 2018-09-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180829_1252'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['depth'], name='d2qc_datapo_depth_c70a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['latitude', 'longitude'], name='d2qc_datapo_latitud_47c2c2_idx'),
        ),
    ]
