# Generated by Django 2.1.dev20180428173945 on 2018-12-04 09:49

import d2qc.data.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0004_dataset_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='filename',
        ),
        migrations.AddField(
            model_name='datafile',
            name='filepath',
            field=models.FileField(blank=True, null=True, upload_to=d2qc.data.models.DataFile.file_store_path),
        ),
        migrations.AddField(
            model_name='datafile',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
