# Generated by Django 2.1.dev20180428173945 on 2018-12-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20181204_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_sets', to='data.DataFile'),
        ),
    ]
