# Generated by Django 2.1.dev20180428173945 on 2018-12-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20181204_1343'),
        ('data', '0003_auto_20181123_0924'),
    ]

    operations = [
    ]
