# Generated by Django 2.1.dev20180428173945 on 2018-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20180913_1329'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['min_lat', 'max_lat', 'min_lon', 'max_lon'], name='d2qc_datase_min_lat_d4a8ec_idx'),
        ),
    ]
