# Generated by Django 2.1.dev20180428173945 on 2019-01-15 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0007_merge_20181217_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='expocode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together={('expocode', 'owner')},
        ),
    ]
