# Generated by Django 2.1.dev20180428173945 on 2019-01-17 13:33

from django.db import migrations
import os
from d2qc.data.glodap.glodap import Glodap
from glodap.util.data_type_dict import DataTypeDict
from d2qc.data.models import DataType

class Migration(migrations.Migration):
    # Do nothing. Caused unneccessary issues...
    dependencies = [
        ('data', '0008_auto_20190115_1525'),
    ]

    operations = [
    ]
