# Generated by Django 2.1.dev20180428173945 on 2018-09-13 14:26

from django.db import migrations
from d2qc.data.sql import *

def fill_bounds(apps, schema_editor):
    DataSet = apps.get_model('data', 'DataSet')
    for ds in DataSet.objects.all():
        cursor = connection.cursor()
        select = """
                SELECT min(latitude) as min_lat, max(latitude) as max_lat,
                min(longitude) as min_lon, max(longitude) as max_lon
                from d2qc_datapoints
        """
        where = ' where data_set_id = %s'
        cursor.execute(select + where, [ds.id])
        ds.min_lat, ds.max_lat, ds.min_lon, ds.max_lon = cursor.fetchone()
        ds.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20180913_1425'),
    ]

    operations = [
        migrations.RunPython(fill_bounds)
    ]
