# Generated by Django 2.1.dev20180428173945 on 2018-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20180913_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='max_lat',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='max_lon',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='min_lat',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='min_lon',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
