# Generated by Django 2.1.dev20180428173945 on 2019-04-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffsetType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'd2qc_offset_types',
            },
        ),
        migrations.RunSQL("""
        INSERT INTO d2qc_offset_types (id, name, description)
            VALUES (1, 'Additive', concat('Additive offset is ',
            'calculated by, for each matching depth, subtracting each ',
            'dependent variable in station 1 by station 2, eg:',
            chr(10),
            'x1=[1,2,3]',
            chr(10),
            'x2=[1.2,2.2,3.2]',
            chr(10),
            '[a-b for a,b in zip(x1,x2)]'));
        """),
        migrations.RunSQL("""
        INSERT INTO d2qc_offset_types (id, name, description)
            VALUES (2, 'Multiplicative', concat('Multiplicative offset is ',
            'calculated by, for each matching depth, dividing each dependent ',
            'variable in station 1 by station 2, eg:',
            chr(10),
            'x1=[1,2,3]',
            chr(10),
            'x2=[1.2,2.2,3.2]',
            chr(10),
            '[a/b for a,b in zip(x1,x2)]'));
        """),
        migrations.RunSQL("""
            SELECT setval('d2qc_offset_types_id_seq', 2, true)
        """),
        migrations.AddField(
            model_name='datatype',
            name='offset_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.OffsetType'),
        ),
        # Multiplicative offsets
        migrations.RunSQL("""
            UPDATE d2qc_data_types set offset_type_id = 2 where original_label in (
            'CFC-11','CFC-12','CFC_11','CFC_12','CTDOXY','DOC','G2cfc11',
            'G2cfc12','G2doc','G2nitrate','G2oxygen','G2phosphate','G2phts25p0',
            'G2silicate','NITRAT','NITRIT','NO2+NO3','OXYGEN','PHSPHT',
            'SILCAT','cfc12','doc','nitrate','nitrite','oxygen',
            'pcfc11','pcfc113','pcfc12','phosphate','phts25p0','silicate'
            )
        """),
    ]
