# Generated by Django 2.1.dev20180428173945 on 2018-09-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20180913_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='station_number',
            field=models.IntegerField(null=True),
        ),
    ]
