# Generated by Django 2.1.dev20180428173945 on 2018-10-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20180914_1139'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dataset',
            name='d2qc_datase_min_lat_d4a8ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='datapoint',
            name='d2qc_datapo_depth_c70a2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='datapoint',
            name='d2qc_datapo_latitud_47c2c2_idx',
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['min_lat', 'max_lat', 'min_lon', 'max_lon'], name='d2qc_data_s_min_lat_ba6b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['depth'], name='d2qc_data_p_depth_34502e_idx'),
        ),
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['latitude', 'longitude'], name='d2qc_data_p_latitud_808fb5_idx'),
        ),
        migrations.AlterModelTable(
            name='datapoint',
            table='d2qc_data_points',
        ),
        migrations.AlterModelTable(
            name='dataset',
            table='d2qc_data_sets',
        ),
        migrations.AlterModelTable(
            name='datatype',
            table='d2qc_data_types',
        ),
        migrations.AlterModelTable(
            name='dataunit',
            table='d2qc_data_units',
        ),
        migrations.AlterModelTable(
            name='datavalue',
            table='d2qc_data_values',
        ),
    ]
