# Generated by Django 2.1.dev20180428173945 on 2019-08-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20190426_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='import_errors',
            field=models.TextField(blank=True),
        ),
    ]
