# Generated by Django 2.1.dev20180428173945 on 2019-08-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_datafile_import_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='import_finnished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='import_started',
            field=models.DateTimeField(null=True),
        ),
        # Update older data
        migrations.RunSQL("""
        UPDATE d2qc_data_files set import_started=created,
        import_finnished=created where import_started is null
        """),
    ]
