# Generated by Django 2.1.dev20180428173945 on 2019-09-20 11:11

import d2qc.data.models.data_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20190812_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='filepath',
            field=models.FileField(null=True, upload_to=d2qc.data.models.data_file.DataFile.file_store_path),
        ),
    ]
