# Generated by Django 2.1.dev20180428173945 on 2019-09-20 11:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20190920_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTypeName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_reference', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_type_names', to='data.DataType')),
            ],
            options={
                'db_table': 'd2qc_data_type_names',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data', django.db.models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='data.DataSet')),
                ('data_type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='data.DataTypeName')),
            ],
            options={
                'db_table': 'd2qc_operations',
            },
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'd2qc_operation_types',
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.OperationType'),
        ),
    ]
