# Generated by Django 2.1.dev20180428173945 on 2019-09-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20190920_1117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datatypename',
            unique_together={('name', 'is_reference')},
        ),
    ]
