# Generated by Django 2.1.dev20180428173945 on 2019-09-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20190920_1225'),
    ]

    operations = [
        # Delete data_type_id's with no data
        migrations.RunSQL("""
            DELETE FROM d2qc_data_types dt1
            using (
                select distinct dt.id
                FROM d2qc_data_types dt
                LEFT JOIN d2qc_data_values dv ON dv.data_type_id=dt.id
                WHERE dv.id IS NULL
            ) dt2
            WHERE dt1.id=dt2.id
        """),
        # Add new field to data values
        migrations.AddField(
            model_name = 'datavalue',
            name = 'data_type_name',
            field = models.ForeignKey(
                null = True,
                on_delete = django.db.models.deletion.CASCADE,
                to = 'data.DataTypeName',
            ),
        ),
        # Insert data_type_names from data_types that are not reference data
        migrations.RunSQL("""
            INSERT INTO d2qc_data_type_names
            (name, is_reference, data_type_id, created, updated)
            SELECT original_label, false, id, now(), now()
            FROM d2qc_data_types
            WHERE original_label<>lower(original_label)
        """),
        # Insert data_type_names from data_types that are reference data
        migrations.RunSQL("""
            INSERT INTO d2qc_data_type_names
            (name, is_reference, data_type_id, created, updated)
            SELECT original_label, true, id, now(), now()
            FROM d2qc_data_types
            WHERE original_label=lower(original_label)
        """),
        # Make oxygen parameter less specific, and in line with the actual data:
        # Oxygen can be either manually measured, sensor measured or a mix
        migrations.RunSQL("""
            UPDATE d2qc_data_types SET identifier='SDN:P01::DOXMZZXX'
            WHERE original_label='oxygen'
        """),
        # Update data_type_name_id field
        migrations.RunSQL("""
            UPDATE d2qc_data_values dv
            SET data_type_name_id = dtn.id
            FROM d2qc_data_type_names dtn
            INNER JOIN d2qc_data_types dt ON dt.id=dtn.data_type_id
            WHERE dv.data_type_name_id IS NULL
            AND dv.data_type_id=dt.id;
        """),
        # Link data_type_names to data_types
        migrations.RunSQL("""
            UPDATE d2qc_data_type_names dtn2
            SET data_type_id=dt.new_id
            FROM (
                SELECT dt2.id as new_id, dt1.id as old_id
                FROM d2qc_data_types dt1
                INNER JOIN d2qc_data_types dt2 ON dt1.identifier=dt2.identifier
                INNER JOIN d2qc_data_type_names dtn ON dt2.id=dtn.data_type_id
                WHERE dtn.is_reference ) AS dt
            WHERE dt.old_id=dtn2.data_type_id
        """),
    ]
