# Generated by Django 2.1.dev20180428173945 on 2019-09-24 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20190920_1225'),
    ]

    operations = [
        # Set data_type_name not nullable
        migrations.AlterField(
            model_name = 'datavalue',
            name = 'data_type_name',
            field = models.ForeignKey(
                on_delete = django.db.models.deletion.CASCADE,
                to = 'data.DataTypeName',
            ),
        ),
        # Change the unique-constraint to use data_type_name
        migrations.AlterUniqueTogether(
            name='datavalue',
            unique_together={('depth', 'data_type_name')},
        ),
        # Make operations
        migrations.RunSQL("""
            INSERT INTO d2qc_operation_types (
                name,
                description,
                created,
                updated
            ) VALUES
            (
                'merge',
                'Merge two parameters, usually ctd-data with bottle data',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            ),
            (
                'normalization',
                'Normalizing alkalinity and DIC with regard to salinity',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            )
        """),
        # Remove data_type field
        migrations.RemoveField(
            model_name='datavalue',
            name='data_type',
        ),
    ]
