# Generated by Django 2.1.dev20180428173945 on 2019-09-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20190925_1447'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE d2qc_data_sets
            SET temp_aut_id = (
                SELECT id FROM d2qc_data_type_names
                WHERE name='temperature' AND is_reference
            )
            WHERE is_reference;
        """),
        migrations.RunSQL("""
            UPDATE d2qc_data_sets
            SET salin_aut_id = (
                SELECT id FROM d2qc_data_type_names
                WHERE name='salinity' AND is_reference
            )
            WHERE is_reference;
        """),
        migrations.RunSQL("""
            UPDATE d2qc_data_sets
            SET press_aut_id = (
                SELECT id FROM d2qc_data_type_names
                WHERE name='pressure' AND is_reference
            )
            WHERE is_reference;
        """),
        migrations.RunSQL("""
            UPDATE d2qc_data_sets
            SET temp_aut_id = (
                SELECT id FROM d2qc_data_type_names
                WHERE name='CTDTMP' AND NOT is_reference
            )
            WHERE NOT is_reference;
        """),
        migrations.RunSQL("""
            UPDATE d2qc_data_sets
            SET salin_aut_id = (
                SELECT id FROM d2qc_data_type_names
                WHERE name='CTDSAL' AND NOT is_reference
            )
            WHERE NOT is_reference;
        """),
        migrations.RunSQL("""
            UPDATE d2qc_data_sets
            SET press_aut_id = (
                SELECT id FROM d2qc_data_type_names
                WHERE name='CTDPRS' AND NOT is_reference
            )
            WHERE NOT is_reference;
        """),
    ]
