# Generated by Django 2.1.dev20180428173945 on 2019-10-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20190927_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='depth_metric',
            field=models.CharField(choices=[('sigma4', 'Sigma 4'), ('depth', 'Depth')], default='sigma4', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='only_qc_controlled_data',
            field=models.BooleanField(default=False),
        ),
    ]
