# Generated by Django 2.1.dev20180428173945 on 2019-10-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20191014_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='depth',
            name='sigma4',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
    ]
