# Generated by Django 2.1.dev20180430021240 on 2019-11-17 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20191101_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatypename',
            name='operation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_type_names', to='data.OperationType'),
        ),
    ]
