"""
Django settings for d2qc project.

Generated by 'django-admin startproject' using Django 2.1.dev20180428173945.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

from .base import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'REPLACE THIS WITH RANDOM KEY!!!!!'

# ALLOWED_HOSTS must be added here
ALLOWED_HOSTS = []


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'd2qc',
        'USER': 'd2qc',
        'PASSWORD': 'd2qc', # ADD CORRECT PASSWORD
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': 'SET storage_engine=INNODB',
        },
    }
}

# Email setup
EMAIL_USE_TLS = True
EMAIL_HOST = ''
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = 587
